2019-11-20 01:50:49:     Reconnected successfully!
2019-11-20 01:50:52:     Game type = "Red bonus tile" : True, "Open tanyao" : True, "Game  length" : tonnansen
2019-11-20 01:50:53:     Reconnected. Resuming game state...
2019-11-20 01:51:02:     --------------------------------------------------
2019-11-20 01:51:02:     Players: [weavile - 4¼‰ - 23000, ¤¢¤é¤Æ¤ó - Èý¶Î - 23000, ¤È¤Þ¤Æ¤£©` - ¶þ¶Î - 25300, ¥´©`¥¼¥ï¥í¥¹ - Èý¶Î - 28700]
2019-11-20 01:51:02:     Dealer: weavile - 4¼‰ - 23000
2019-11-20 01:51:02:  
2019-11-20 01:51:07:     [Player 3] draws a tile...
2019-11-20 01:51:10: 
2019-11-20 01:51:10: Unexpected exception
Traceback (most recent call last):
  File "C:\Users\j4903\Documents\MahjongAI\main.py", line 17, in connect_and_play
    return client.start_game()
  File "C:\Users\j4903\Documents\MahjongAI\client\tenhou_client.py", line 129, in start_game
    if self._handle_draw_tile(msg):
  File "C:\Users\j4903\Documents\MahjongAI\client\tenhou_client.py", line 534, in _handle_draw_tile
    discard_tile_136 = self.game_table.bot.to_discard_tile()
  File "C:\Users\j4903\Documents\MahjongAI\agents\MahjongAgent.py", line 864, in to_discard_tile
    tile_weight = self.yaku_goal_list(yaku_dict)
  File "C:\Users\j4903\Documents\MahjongAI\agents\MahjongAgent.py", line 736, in yaku_goal_list
    temp_p = 1 - (1 - ((4 - self.game_table.revealed_tiles[item])/self.game_table.count_remaining_tiles))**5
IndexError: list index out of range
2019-11-20 01:51:10: End the game...
2019-11-20 01:51:10:     Game was ended unexpected
2019-11-20 01:51:10: 
